"""add_wallet_and_transaction_tables

Revision ID: 30c4d1b5ac23
Revises: 360997d60f92
Create Date: 2026-03-26 13:24:16.625847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c4d1b5ac23'
down_revision: Union[str, Sequence[str], None] = '360997d60f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
