"""Add payout invoices and project members

Revision ID: b81a8934aa42
Revises: b5399d995f8c
Create Date: 2026-03-28 18:34:54.080018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81a8934aa42'
down_revision: Union[str, Sequence[str], None] = 'b5399d995f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('total_payout_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('team_payout_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('company_payout_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_payout_invoices_id'), 'payout_invoices', ['id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    op.drop_index(op.f('ix_payout_invoices_id'), table_name='payout_invoices')
    op.drop_table('payout_invoices')
    # ### end Alembic commands ###
